//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Libb
{
    using System;
    using System.Collections.Generic;
    
    public partial class Borrowing
    {
        public int ID { get; set; }
        public Nullable<int> ReaderID { get; set; }
        public Nullable<int> BookID { get; set; }
        public Nullable<System.DateTime> DateOfBorrowing { get; set; }
        public Nullable<System.DateTime> DateOfReturning { get; set; }
        public string IsReturned { get; set; }
    
        public virtual Book Book { get; set; }
        public virtual Reader Reader { get; set; }
    }
}
